// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menu-connector-label'
  | 'menuitem-configure-mcp-label'
  | 'menuitem-export-label'
  | 'menuitem-export-selected-label'
  | 'startup-begin'
  | 'startup-finish';
