// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "mcp.enabled": boolean;
      "mcp.clientPreset": string;
      "mcp.clientExecutablePath": string;
      "mcp.runtimePath": string;
      "mcp.adapterPath": string;
      "mcp.clientConfigPath": string;
    };
  }
}
